version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: academic-db
    environment:
      - POSTGRES_DB=academic-api
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - academic-network
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: karolina.souza@estudante.ufjf.br
      PGADMIN_DEFAULT_PASSWORD: ${DB_PASSWORD}
      PGADMIN_DISABLE_POSTFIX: true
    ports:
      - "8888:80"
    networks:
      - academic-network
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.25'

volumes:
  postgres_data:

networks:
  academic-network:
