version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: academic-db
    environment:
      - POSTGRES_DB=academic-api
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - academic-network

volumes:
  postgres_data:

networks:
  academic-network:
