version: '2.4'

services:
  postgres:
    image: postgres:15-alpine
    container_name: academic-db-v2
    environment:
      - POSTGRES_DB=academic-api
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - academic-network
    mem_limit: 256m
    cpus: 0.5
    command: >
      postgres
      -c shared_buffers=128MB
      -c work_mem=4MB
      -c effective_cache_size=256MB
      -c max_connections=50
      -c synchronous_commit=off
      -c fsync=off
      -c full_page_writes=off
      -c log_min_messages=warning

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-academic

    environment:
      PGADMIN_DEFAULT_EMAIL: karolina.souza@estudante.ufjf.br
      PGADMIN_DEFAULT_PASSWORD: ${DB_PASSWORD}
      PGADMIN_DISABLE_POSTFIX: true
    ports:
      - "8888:80"
    networks:
      - academic-network
    mem_limit: 128m
    cpus: 0.25

volumes:
  postgres_data:

networks:
  academic-network:

