CREATE TABLE salary_structures (
                                   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   job_position VARCHAR(255) NOT NULL,
                                   level VARCHAR(255) NOT NULL,
                                   base_salary NUMERIC(10, 2) NOT NULL,

                                   CONSTRAINT uk_salary_structure_job_level UNIQUE (job_position, level)
);