CREATE TABLE payroll_records (
                                 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 person_id BIGINT NOT NULL,
                                 reference_month DATE NOT NULL,
                                 base_salary NUMERIC(10, 2) NOT NULL,
                                 bonuses NUMERIC(10, 2),
                                 deductions NUMERIC(10, 2),
                                 net_pay NUMERIC(10, 2) NOT NULL,
                                 status VARCHAR(255) NOT NULL,
                                 payment_date DATE,
                                 created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                                 CONSTRAINT fk_payroll_person FOREIGN KEY (person_id) REFERENCES people(id)
);