CREATE TABLE purchase_orders (
                                 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 requester_id BIGINT NOT NULL,
                                 supplier VARCHAR(255) NOT NULL,
                                 description TEXT NOT NULL,
                                 amount NUMERIC(10, 2) NOT NULL,
                                 status VARCHAR(255) NOT NULL,
                                 order_date DATE NOT NULL,
                                 due_date DATE,
                                 payment_date DATE,
                                 created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                                 CONSTRAINT fk_po_requester FOREIGN KEY (requester_id) REFERENCES employees(id)
);