CREATE TABLE purchase_requests (
                                   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   requester_id BIGINT NOT NULL,
                                   item_name VARCHAR(255) NOT NULL,
                                   quantity INT NOT NULL,
                                   justification TEXT,
                                   status VARCHAR(255) NOT NULL,
                                   created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                                   CONSTRAINT fk_pr_requester FOREIGN KEY (requester_id) REFERENCES employees(id)
);