CREATE TABLE assessment_definitions (
                                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        course_section_id BIGINT NOT NULL,
                                        title VARCHAR(255) NOT NULL,
                                        type VARCHAR(50) NOT NULL,
                                        assessment_date DATE,
                                        weight NUMERIC(5, 2),

                                        CONSTRAINT fk_assessment_def_to_course_section
                                            FOREIGN KEY(course_section_id)
                                                REFERENCES course_sections(id)
                                                ON DELETE CASCADE
);