CREATE TABLE teacher_notes (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               enrollment_id BIGINT NOT NULL,
                               author_id BIGINT NOT NULL,
                               content TEXT NOT NULL,
                               created_at TIMESTAMP WITHOUT TIME ZONE,
                               CONSTRAINT fk_teacher_notes_to_enrollment FOREIGN KEY (enrollment_id) REFERENCES enrollments(id),
                               CONSTRAINT fk_teacher_notes_to_teacher FOREIGN KEY (author_id) REFERENCES teachers(id)
);